### ISSUE TITLE
If you used radio once, it keeps draining the battery

### ISSUE THREAD

**Issue by Remi321** [terminator-97/SCPUtils#25]
After the new update of today, which fixed the bug not being able to talk. if you talk on the radio once with V the radio will act like it is still being used and drains the battery about 1 to 1,5 % per second. I have compared this to another server without SCPUtils installed and there this does not happen.

**Comment by Remi321** [comment]
> After the new update of today, which fixed the bug not being able to talk. if you talk on the radio once with V the radio will act like it is still being used and drains the battery about 1 to 1,5 % per second. I have compared this to another server without SCPUtils installed and there this does not happen.

This bug is still here on exiled 5.0

**Comment by terminator-97** [comment]
Hi, this bug will be verified and fixed, thanks for reporting.
