### ISSUE TITLE
Custom Badge doesn't go back to original Badge

### ISSUE THREAD

**Issue by Miggas** [terminator-97/SCPUtils#30]
### Describe your bug

Hi, after giving myself a custom badge (I had the owner badge before), I can't revert it back, any command I've tried didn't work, the command I tried are:
- scputils_cbadge Miggas none
- scpu_remove_badge Miggas
- scpu_cb Miggas none
- issue_badge Miggas owner 0
- scputils_revoke_badge Miggas
- scputils_remove_previous_badge Miggas

Even deleting the custom badge text in the database didn't work
Am I doing something wrong or is it bugged?

### SCPUtils Version

6.2.2

**Comment by Bay62** [comment]
This bug will be fixed in the next update of SCPUtils! Thanks you for reporting.

@Miggas
