### ISSUE TITLE
The plugin reports an error in the console

### ISSUE THREAD

**Issue by RJCooLEST** [terminator-97/SCPUtils#5]
![image](https://user-images.githubusercontent.com/56374469/90541383-1f60f700-e1b5-11ea-9078-e9f3a56fb0e9.png)

The announcement message appears to be working

**Comment by terminator-97** [comment]
Try to use last version

**Comment by terminator-97** [comment]
I suppose the issue is resolved, if you're still having same problem feel free to reopen it.

**Comment by RJCooLEST** [comment]
tk.Well done.
