### ISSUE TITLE
Error in the Console when a Player Joins

### ISSUE THREAD

**Issue by SoraCent** [terminator-97/SCPUtils#6]
Good Day,

Everytime when a Player joins my Server there is an Huge Error.

![grafik](https://user-images.githubusercontent.com/46794893/103158992-44e5b900-47c4-11eb-9339-7dca9c7b3ee0.png)

I'm using the Latest Release of SCPUtils and the Latest version of Exiled.

Idk what causes this error but the Server works fine.

**Comment by terminator-97** [comment]
Hello, are the stats working fine?

**Comment by SoraCent** [comment]
Yes, I testet the Commands and every command worked also getting infos about users

**Comment by terminator-97** [comment]
On january i will release an update of SCPUtils which also include some bugfixes, try with that one once i release it.
